### ISSUE TITLE
Problem with the slash in the file path in Windows.

### ISSUE THREAD

**Issue by S-le** [ls-age/devtools#60]
Property ID in the "load" Rollup hook contains forward-slashes. But **files** Set contains backward-slashes. 
This patch can fix it:
`load(id) {
      files.delete(id.split('/').join('\\'));
 }`

This problem in **rollup-plugin-unused**.

**Comment by LukasHechenberger** [comment]
Looks like the patch only works for windows 😅 I think you could use node's path module to create cross platform compatible paths instead. Can you try it out and create a pr?

**Comment by S-le** [comment]
Ok. I'll do it.

**Comment by LukasHechenberger** [comment]
Fixed in #61
